# Generated by Django 4.2.16 on 2026-02-27 02:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("eve_sde", "0012_alter_constellation_region"),
        ("taxtools", "0025_corptaxperservicemoduleconfiguration_structure_type_filter"),
    ]

    operations = [
        migrations.AlterField(
            model_name="characterrattingtaxconfiguration",
            name="region_filter",
            field=models.ManyToManyField(blank=True, to="eve_sde.region"),
        ),
        migrations.AlterField(
            model_name="corptaxperservicemoduleconfiguration",
            name="region_filter",
            field=models.ManyToManyField(
                blank=True,
                help_text="Regions to limit this tax to.",
                to="eve_sde.region",
            ),
        ),
        migrations.AlterField(
            model_name="corptaxperservicemoduleconfiguration",
            name="structure_type_filter",
            field=models.ManyToManyField(
                blank=True,
                limit_choices_to={"group__category_id": 65},
                to="eve_sde.itemtype",
            ),
        ),
    ]
